package qrpc

import (
	"bytes"
	"context"
	"crypto/tls"
	"fmt"
	"sync"
	"time"

	"github.com/quic-go/quic-go"
	"google.golang.org/protobuf/proto"
)

// MethodHandler is the handler invoked by the server for a single unary RPC
// method. The srv argument is the service implementation registered by the
// caller (placed before ctx to mirror the gRPC generated handler convention).
// The payload argument contains the raw serialized request bytes. The handler
// is responsible for unmarshaling the payload into the appropriate message type
// and returning the response as a proto.Message.
type MethodHandler func(srv any, ctx context.Context, payload []byte) (proto.Message, error)

// MethodDesc describes a single unary RPC method within a service.
type MethodDesc struct {
	MethodName string
	Handler    MethodHandler
}

// ServiceDesc describes a protobuf service for registration with a Server. It
// is typically generated by protoc-gen-qrpc.
type ServiceDesc struct {
	ServiceName string
	Methods     []MethodDesc
}

// Server listens for QUIC connections and dispatches incoming RPC calls to
// registered service implementations.
type Server struct {
	// HandlerTimeout, if non-zero, is the maximum duration allowed for a
	// single RPC handler to complete. When the timeout expires the handler's
	// context is cancelled. A zero value means no per-RPC timeout is applied
	// and handlers rely on the QUIC idle timeout instead.
	HandlerTimeout time.Duration

	mu       sync.Mutex
	services map[string]*serviceInfo
	serving  bool
	wg       sync.WaitGroup
}

// serviceInfo holds the implementation and method dispatch table for a
// registered service.
type serviceInfo struct {
	impl    any
	methods map[string]MethodHandler
}

// NewServer returns a new Server with no registered services.
func NewServer() *Server {
	return &Server{
		services: make(map[string]*serviceInfo),
	}
}

// RegisterService registers a service implementation described by desc. This
// method is typically called by generated registration functions (e.g.
// RegisterGreeterServer) rather than directly by application code. All
// services must be registered before calling Serve or ListenAndServe. It
// panics if the service is already registered or if the server is already
// serving.
func (s *Server) RegisterService(desc *ServiceDesc, impl any) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.serving {
		panic("qrpc: RegisterService called after Serve")
	}
	if _, ok := s.services[desc.ServiceName]; ok {
		panic(fmt.Sprintf("qrpc: service %q already registered", desc.ServiceName))
	}

	info := &serviceInfo{
		impl:    impl,
		methods: make(map[string]MethodHandler),
	}
	for _, m := range desc.Methods {
		info.methods[m.MethodName] = m.Handler
	}
	s.services[desc.ServiceName] = info
}

// ListenAndServe starts listening for QUIC connections on addr using the
// provided TLS configuration. The TLS configuration must include at least one
// certificate. The ALPN protocol is set automatically. Cancelling ctx stops
// acceptance of new connections; Serve then waits for in-flight handlers to
// complete before returning.
func (s *Server) ListenAndServe(ctx context.Context, addr string, tlsConfig *tls.Config) error {
	tc := tlsConfig.Clone()
	tc.NextProtos = []string{alpnProtocol}

	listener, err := quic.ListenAddr(addr, tc, defaultQUICConfig())
	if err != nil {
		return fmt.Errorf("qrpc: listen: %w", err)
	}
	return s.Serve(ctx, listener)
}

// Serve accepts incoming connections from the provided QUIC listener and
// dispatches RPC calls. Cancelling ctx stops acceptance of new connections and
// streams. Serve blocks until all in-flight handlers have completed and then
// returns ctx.Err().
func (s *Server) Serve(ctx context.Context, listener *quic.Listener) error {
	s.mu.Lock()
	s.serving = true
	s.mu.Unlock()

	var acceptErr error
	for {
		conn, err := listener.Accept(ctx)
		if err != nil {
			acceptErr = err
			break
		}
		s.wg.Add(1)
		go func() {
			defer s.wg.Done()
			s.handleConn(ctx, conn)
		}()
	}

	s.wg.Wait()

	if ctx.Err() != nil {
		return ctx.Err()
	}
	return fmt.Errorf("qrpc: accept connection: %w", acceptErr)
}

// handleConn accepts streams from a single QUIC connection and dispatches each
// as an independent RPC call.
func (s *Server) handleConn(ctx context.Context, conn quic.Connection) {
	for {
		stream, err := conn.AcceptStream(ctx)
		if err != nil {
			return
		}
		s.wg.Add(1)
		go func() {
			defer s.wg.Done()
			s.handleStream(stream)
		}()
	}
}

// handleStream reads a single RPC request from the stream, dispatches it to
// the appropriate method handler, and writes the response. The services map is
// accessed without a lock because it is immutable after Serve is called.
func (s *Server) handleStream(stream quic.Stream) {
	defer stream.Close()

	method, payload, buf, err := readRequest(stream)
	if err != nil {
		return
	}
	defer buf.release()

	service, methodName, err := splitMethod(method)
	if err != nil {
		writeErrorResponse(stream, err)
		return
	}

	// The string(b) conversions in map lookups are optimized by the Go
	// compiler to avoid heap allocation.
	info, ok := s.services[string(service)]
	if !ok {
		writeErrorResponse(stream, fmt.Errorf("qrpc: unknown service %q", service))
		return
	}

	handler, ok := info.methods[string(methodName)]
	if !ok {
		writeErrorResponse(stream, fmt.Errorf("qrpc: unknown method %q on service %q", methodName, service))
		return
	}

	ctx := stream.Context()
	if s.HandlerTimeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, s.HandlerTimeout)
		defer cancel()
	}

	resp, err := handler(info.impl, ctx, payload)
	if err != nil {
		writeErrorResponse(stream, err)
		return
	}

	marshalResponse(stream, resp)
}

// splitMethod splits a method byte slice of the form "/service.Name/Method"
// into its service and method components as byte slices, avoiding any string
// allocation.
func splitMethod(method []byte) (service, meth []byte, err error) {
	if len(method) == 0 || method[0] != '/' {
		return nil, nil, fmt.Errorf("qrpc: invalid method %q", method)
	}
	rest := method[1:]
	i := bytes.IndexByte(rest, '/')
	if i <= 0 || i == len(rest)-1 {
		return nil, nil, fmt.Errorf("qrpc: invalid method %q", method)
	}
	return rest[:i], rest[i+1:], nil
}
