package qrpc

import (
	"context"
	"crypto/tls"
	"fmt"
	"sync"
	"time"

	"github.com/quic-go/quic-go"
)

// MethodHandler is the handler invoked by the server for a single unary RPC
// method. The payload argument contains the raw serialized request bytes. The
// buf argument is a scratch buffer from the pool that the handler should pass
// to proto.MarshalOptions{}.MarshalAppend to avoid per-call allocations. The
// returned byte slice may alias buf or be a new allocation. Typically, a
// MethodHandler is a closure generated by protoc-gen-qrpc that captures the
// concrete service implementation.
type MethodHandler func(ctx context.Context, payload, buf []byte) ([]byte, error)

// MethodDesc describes a single unary RPC method within a service.
type MethodDesc struct {
	MethodName string
	Handler    MethodHandler
}

// ServiceDesc describes a protobuf service for registration with a Server. It
// is typically generated by protoc-gen-qrpc.
type ServiceDesc struct {
	ServiceName string
	Methods     []MethodDesc
}

// Server listens for QUIC connections and dispatches incoming RPC calls to
// registered service implementations.
type Server struct {
	// HandlerTimeout, if non-zero, is the maximum duration allowed for a
	// single RPC handler to complete. When the timeout expires the handler's
	// context is cancelled. A zero value means no per-RPC timeout is applied
	// and handlers rely on the QUIC idle timeout instead.
	HandlerTimeout time.Duration

	mu       sync.Mutex
	handlers map[string]MethodHandler
	serving  bool
	wg       sync.WaitGroup
}

// NewServer returns a new Server with no registered services.
func NewServer() *Server {
	return &Server{
		handlers: make(map[string]MethodHandler),
	}
}

// RegisterService registers a service described by desc. This method is
// typically called by generated registration functions (e.g.
// RegisterGreeterServer) rather than directly by application code. All
// services must be registered before calling Serve or ListenAndServe. It
// panics if any method is already registered or if the server is already
// serving.
func (s *Server) RegisterService(desc *ServiceDesc) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.serving {
		panic("qrpc: RegisterService called after Serve")
	}

	for _, m := range desc.Methods {
		key := "/" + desc.ServiceName + "/" + m.MethodName
		if _, ok := s.handlers[key]; ok {
			panic(fmt.Sprintf("qrpc: method %q already registered", key))
		}
		s.handlers[key] = m.Handler
	}
}

// ListenAndServe starts listening for QUIC connections on addr using the
// provided TLS configuration. The TLS configuration must include at least one
// certificate. The ALPN protocol is set automatically. Cancelling ctx stops
// acceptance of new connections; Serve then waits for in-flight handlers to
// complete before returning.
func (s *Server) ListenAndServe(ctx context.Context, addr string, tlsConfig *tls.Config) error {
	tc := tlsConfig.Clone()
	tc.NextProtos = []string{alpnProtocol}

	listener, err := quic.ListenAddr(addr, tc, defaultQUICConfig())
	if err != nil {
		return fmt.Errorf("qrpc: listen: %w", err)
	}
	return s.Serve(ctx, listener)
}

// Serve accepts incoming connections from the provided QUIC listener and
// dispatches RPC calls. Cancelling ctx stops acceptance of new connections and
// streams. Serve blocks until all in-flight handlers have completed, closes
// the listener, and then returns ctx.Err().
func (s *Server) Serve(ctx context.Context, listener *quic.Listener) error {
	s.mu.Lock()
	s.serving = true
	s.mu.Unlock()

	defer listener.Close()

	var acceptErr error
	for {
		conn, err := listener.Accept(ctx)
		if err != nil {
			acceptErr = err
			break
		}
		s.wg.Add(1)
		go func() {
			defer s.wg.Done()
			s.handleConn(ctx, conn)
		}()
	}

	s.wg.Wait()

	if ctx.Err() != nil {
		return ctx.Err()
	}
	return fmt.Errorf("qrpc: accept connection: %w", acceptErr)
}

// handleConn accepts streams from a single QUIC connection and dispatches each
// as an independent RPC call.
func (s *Server) handleConn(ctx context.Context, conn quic.Connection) {
	for {
		stream, err := conn.AcceptStream(ctx)
		if err != nil {
			return
		}
		s.wg.Add(1)
		go func() {
			defer s.wg.Done()
			s.handleStream(stream)
		}()
	}
}

// handleStream reads a single RPC request from the stream, dispatches it to
// the appropriate method handler, and writes the response. The handlers map is
// accessed without a lock because it is immutable after Serve is called.
func (s *Server) handleStream(stream quic.Stream) {
	defer stream.Close()

	method, payload, reqBuf, err := readRequest(stream)
	if err != nil {
		return
	}
	defer reqBuf.release()

	// The string([]byte) conversion in a map lookup is optimized by the Go
	// compiler to avoid heap allocation.
	handler, ok := s.handlers[string(method)]
	if !ok {
		writeErrorResponse(stream, fmt.Errorf("qrpc: unknown method %q", method))
		return
	}

	ctx := stream.Context()
	if s.HandlerTimeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, s.HandlerTimeout)
		defer cancel()
	}

	bp := getBuf(0)
	resp, err := handler(ctx, payload, *bp)
	if err != nil {
		*bp = resp
		putBuf(bp)
		writeErrorResponse(stream, err)
		return
	}

	if err := writeResponse(stream, resp); err != nil {
		writeErrorResponse(stream, err)
	}
	*bp = resp
	putBuf(bp)
}
