// Command protoc-gen-qrpc is a protoc plugin that generates Go client and
// server stubs for the qrpc framework. Install and use it with:
//
//	go install github.com/acycl/qrpc/cmd/protoc-gen-qrpc@latest
//	protoc --qrpc_out=. --qrpc_opt=paths=source_relative your_service.proto
package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(generate)
}

// generate processes all proto files and emits qrpc service stubs for each
// file that contains at least one service definition.
func generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate || len(f.Services) == 0 {
			continue
		}
		if err := checkNoStreaming(f); err != nil {
			return err
		}
		generateFile(plugin, f)
	}
	return nil
}

// checkNoStreaming returns an error if any method in f uses streaming, which
// qrpc does not support.
func checkNoStreaming(f *protogen.File) error {
	for _, svc := range f.Services {
		for _, m := range svc.Methods {
			if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
				return fmt.Errorf(
					"%s: method %s.%s uses streaming, which is not supported by qrpc",
					f.Desc.Path(), svc.Desc.FullName(), m.Desc.Name(),
				)
			}
		}
	}
	return nil
}

// generateFile emits a single _qrpc.pb.go file containing client and server
// stubs for every service defined in f.
func generateFile(plugin *protogen.Plugin, f *protogen.File) {
	filename := f.GeneratedFilenamePrefix + "_qrpc.pb.go"
	g := plugin.NewGeneratedFile(filename, f.GoImportPath)

	g.P("// Code generated by protoc-gen-qrpc. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	qrpcPkg := protogen.GoImportPath("github.com/acycl/qrpc")
	contextPkg := protogen.GoImportPath("context")
	protoPkg := protogen.GoImportPath("google.golang.org/protobuf/proto")

	for _, svc := range f.Services {
		generateService(g, svc, qrpcPkg, contextPkg, protoPkg)
	}
}

// generateService emits server interface, registration function, method
// handlers, service descriptor, client interface, and client implementation
// for a single protobuf service. All methods must be unary; streaming methods
// are rejected earlier by checkNoStreaming.
func generateService(g *protogen.GeneratedFile, svc *protogen.Service, qrpcPkg, contextPkg, protoPkg protogen.GoImportPath) {
	svcName := svc.GoName
	fullName := string(svc.Desc.FullName())
	methods := svc.Methods

	// --- Server interface ---
	g.P("// ", svcName, "Server is the server API for the ", svcName, " service.")
	g.P("type ", svcName, "Server interface {")
	for _, m := range methods {
		g.P(m.GoName, "(", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", *", g.QualifiedGoIdent(m.Input.GoIdent), ") (*", g.QualifiedGoIdent(m.Output.GoIdent), ", error)")
	}
	g.P("}")
	g.P()

	// --- Registration function ---
	g.P("// Register", svcName, "Server registers a ", svcName, "Server implementation with the qrpc server.")
	g.P("func Register", svcName, "Server(s *", g.QualifiedGoIdent(qrpcPkg.Ident("Server")), ", srv ", svcName, "Server) {")
	g.P("s.RegisterService(&", g.QualifiedGoIdent(qrpcPkg.Ident("ServiceDesc")), "{")
	g.P("ServiceName: ", quote(fullName), ",")
	g.P("Methods: []", g.QualifiedGoIdent(qrpcPkg.Ident("MethodDesc")), "{")
	for _, m := range methods {
		g.P("{")
		g.P("MethodName: ", quote(m.GoName), ",")
		g.P("Handler: func(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", payload, buf []byte) ([]byte, error) {")
		g.P("in := new(", g.QualifiedGoIdent(m.Input.GoIdent), ")")
		g.P("if err := ", g.QualifiedGoIdent(protoPkg.Ident("Unmarshal")), "(payload, in); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("out, err := srv.", m.GoName, "(ctx, in)")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return ", g.QualifiedGoIdent(protoPkg.Ident("MarshalOptions")), "{}.MarshalAppend(buf, out)")
		g.P("},")
		g.P("},")
	}
	g.P("},")
	g.P("})")
	g.P("}")
	g.P()

	// --- Client interface ---
	g.P("// ", svcName, "Client is the client API for the ", svcName, " service.")
	g.P("type ", svcName, "Client interface {")
	for _, m := range methods {
		g.P(m.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", in *", g.QualifiedGoIdent(m.Input.GoIdent), ") (*", g.QualifiedGoIdent(m.Output.GoIdent), ", error)")
	}
	g.P("}")
	g.P()

	// --- Client implementation ---
	unexportedClient := unexport(svcName) + "Client"
	g.P("type ", unexportedClient, " struct {")
	g.P("cc *", g.QualifiedGoIdent(qrpcPkg.Ident("ClientConn")))
	g.P("}")
	g.P()

	g.P("// New", svcName, "Client returns a new ", svcName, "Client backed by the given connection.")
	g.P("func New", svcName, "Client(cc *", g.QualifiedGoIdent(qrpcPkg.Ident("ClientConn")), ") ", svcName, "Client {")
	g.P("return &", unexportedClient, "{cc: cc}")
	g.P("}")
	g.P()

	for _, m := range methods {
		methodPath := fmt.Sprintf("/%s/%s", fullName, m.GoName)
		g.P("func (c *", unexportedClient, ") ", m.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", in *", g.QualifiedGoIdent(m.Input.GoIdent), ") (*", g.QualifiedGoIdent(m.Output.GoIdent), ", error) {")
		g.P("out := new(", g.QualifiedGoIdent(m.Output.GoIdent), ")")
		g.P("err := c.cc.Invoke(ctx, ", quote(methodPath), ", in, out)")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return out, nil")
		g.P("}")
		g.P()
	}
}

// quote returns a Go string literal for s.
func quote(s string) string {
	return fmt.Sprintf("%q", s)
}

// unexport returns s with its first letter lowercased.
func unexport(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
